descriptions:
  cv.txt: curriculum vitae
  now.txt: what i'm doing now
  man.txt: manual page
  changelog.txt: site changelog
  stats.txt: site statistics
dates:
  changelog.txt: 2026-01-23
  cv.txt: 2026-01-23
  man.txt: 2026-03-26
  now.txt: 2026-01-23
  stats.txt: 2026-01-23
